### ISSUE TITLE
Not work in Unity 2021.3.23f1

### ISSUE THREAD

**Issue by FrameVolt** [crazyjackel/redmoon-reactiveKit#3]
Hi Bro, I install this package, but compile error shows below:

Library\PackageCache\io.crazyjackel.redmoon-reactivekit@8bdfa4a811\Runtime\Scripts\ViewModel.cs(7,15): error CS0234: The type or namespace name 'Injector' does not exist in the namespace 'RedMoon' (are you missing an assembly reference?)

Library\PackageCache\io.crazyjackel.redmoon-reactivekit@8bdfa4a811\Runtime\Scripts\ViewModel.cs(11,58): error CS0246: The type or namespace name 'IClient' could not be found (are you missing a using directive or an assembly reference?)

**Comment by crazyjackel** [comment]
Thank you for bringing this to my attention. I haven’t taken a look at the code in quite some time, but my estimation is that some of my preprocessor macros are inserting code that is due from my dependency injector project. Basically the flag that you have my other assembly package is being triggered as true, when you do not.

I would appreciate further details with that in mind. I will take a look at it and get back again within 24 hours. Cheers!

**Comment by crazyjackel** [comment]
Make sure you have the following dependencies installed.

"gitDependencies": {
    "com.neuecc.unirx": "https://github.com/neuecc/UniRx.git?path=Assets/Plugins/UniRx/Scripts",
    "io.crazyjackel.redmoon-depinjector": "https://github.com/crazyjackel/redmoon-depInjector.git#1.0.1"
  },

**Comment by FrameVolt** [comment]
Thanks bro!
